import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { test } from 'node:test'

const ROOT = new URL('..', import.meta.url).pathname
const html = readFileSync(join(ROOT, 'demo/index.html'), 'utf8')

/**
 * These matrices were generated by the same algorithm and then decoded back to
 * their URLs with OpenCV's QR detector — the check a phone camera actually
 * performs. Pinning them here means the copy inlined in demo/index.html is what
 * gets tested, not a copy that happens to live somewhere else.
 */
const EXPECTED = JSON.parse(readFileSync(join(ROOT, 'tests/fixtures/qr/matrices.json'), 'utf8'))

/** Pull the encoder straight out of the shipped file and run it. */
function loadInlinedEncoder() {
  const start = html.indexOf('function qrMatrix(')
  const end = html.indexOf('(function(){\n  const box=document.getElementById(\'qrbox\')')
  assert.ok(start > 0 && end > start, 'qrMatrix is not in demo/index.html any more')
  const src = html.slice(start, end)
  return new Function(`${src}; return qrMatrix`)()
}

test('the QR encoder inlined in the demo reproduces the decoded fixtures', () => {
  const qrMatrix = loadInlinedEncoder()
  for (const [url, expected] of Object.entries(EXPECTED)) {
    const got = qrMatrix(url)
    assert.ok(got, `encoder refused ${url}`)
    assert.deepEqual(
      got.map((r) => [...r].join('')),
      expected,
      `QR for ${url} no longer matches the decode-verified fixture`,
    )
  }
})

test('the QR is built from the live origin, not a hardcoded domain', () => {
  assert.match(html, /location\.origin/, 'the QR would point at the wrong deployment')
  assert.ok(
    !/qrMatrix\(['"]https:\/\//.test(html),
    'a URL is hardcoded into the QR instead of read from location',
  )
})

test('the encoder covers the URL lengths a Vercel deployment can produce', () => {
  const qrMatrix = loadInlinedEncoder()
  const long = 'https://bhavsetu-git-some-quite-long-branch-name-fractal-verse.vercel.app'
  assert.ok(qrMatrix(long), `encoder gave up on a ${long.length}-char preview URL`)
  assert.ok(qrMatrix('https://x.co'), 'encoder failed on a short URL')
})
