/**
 * Regenerates docs/marathi-review.md from src/i18n/mr.json.
 *
 * Every key still carrying a TODO-mr marker becomes a checklist line with the
 * English meaning and where it appears on screen. Run it after any session that
 * adds strings: `npm run marathi-review`.
 *
 * gallery.* keys are excluded on purpose — /gallery is a developer surface, not
 * a farmer screen, and its labels never reach a farmer.
 */
import { readFileSync, writeFileSync } from 'node:fs'

const mr = JSON.parse(readFileSync(new URL('../src/i18n/mr.json', import.meta.url), 'utf8'))
const en = JSON.parse(readFileSync(new URL('../src/i18n/en.json', import.meta.url), 'utf8'))

/** Where each string appears, and any constraint the reviewer has to respect. */
const CONTEXT = {
  'verdict.reasonsTitle': 'Heading of the sheet that opens when you tap विका / थांबा / सावध.',
  'verdict.reasonsHint': 'Tiny text on the verdict chip itself, telling you it can be tapped. 2–3 words.',
  'verdict.reason.arrivalsFalling': 'Reason 1 in that sheet. Plain speech, how a trader would say it.',
  'verdict.reason.noRain': 'Reason 2 in that sheet.',
  'verdict.reason.festivalDemand': 'Reason 3 in that sheet.',
  'offline.badge': 'Small grey badge in the header when the data is cached. {time} is a clock time.',
  'error.retry': 'Button under "भाव मिळाला नाही." 1–2 words.',
  'trust.label': 'Read aloud for the buyer trust bar. Not shown on screen.',
  'deduction.bid': 'Money math on a bid: bid − transport − cess = in hand. Label for the bid.',
  'deduction.transport': 'Same math, label for the transport deduction.',
  'deduction.cess': 'Same math, label for the mandi cess deduction.',
  'deduction.inHand': 'Same math, the bold final line. Master prompt calls it "tumhala milel" — confirm the exact form.',
  'money.seasonTotal': 'Label above the big season total on the पैसे screen.',
  'money.extraEarned': 'Label on the closing demo card: what the farmer earned above the harvest-day price.',
  'voice.mic': 'The word under the big mic button. ONE short word, must fit a 72px circle.',
  'voice.speaker': 'The word under the speaker icon, top right of every screen. ONE short word.',
  'common.close': 'Close button on every sheet. 1 word.',
  'common.stepOf': 'Progress in the 3-step add-lot flow. {current} and {total} are numbers.',
}

const TODO = /^TODO-mr:\s*/
const keys = Object.keys(mr).filter(
  (k) => k !== '_readme' && TODO.test(mr[k]) && !k.startsWith('gallery.'),
)

const lines = [
  '# Marathi review checklist',
  '',
  '_Generated by `npm run marathi-review` from `src/i18n/mr.json`. Do not edit by hand._',
  '',
  `${keys.length} strings in the farmer app still have no Marathi. \`docs/frontend-spec.md\``,
  'supplies none for these, and CLAUDE.md rule 2 forbids machine-translating them, so',
  'the app currently shows the English meaning in the Marathi build. Every one of them',
  'is visible at `/gallery` under Strings, badged `TODO-mr`.',
  '',
  'Send the block below as one WhatsApp message. Replies come back as',
  '`key = मराठी`, and land in `src/i18n/mr.json`.',
  '',
  '---',
  '',
  '```',
  '*BhavSetu — मराठी हवी आहे*',
  '',
  `${keys.length} strings need Marathi. The app shows English for these right now.`,
  'Reply with the number and the Marathi, e.g.  1 = कारण',
  '',
  'Rules: farmer speech, not textbook Marathi. Short. No English words',
  'unless a farmer would actually say them.',
  '',
]

keys.forEach((key, i) => {
  lines.push(`${String(i + 1).padStart(2, ' ')}. ${en[key]}`)
  lines.push(`    ${CONTEXT[key] ?? 'TODO: describe where this appears.'}`)
  lines.push('')
})

lines.push('```', '', '---', '', '## Key map', '', '| # | Key | English |', '|---|---|---|')
keys.forEach((key, i) => {
  lines.push(`| ${i + 1} | \`${key}\` | ${en[key]} |`)
})
lines.push(
  '',
  '## Also outstanding',
  '',
  '- The whole of `src/i18n/hi.json` awaits Hindi — every value is marked `TODO-hi`.',
  '- 17 `gallery.*` keys are developer-surface labels and deliberately excluded here.',
  '',
)

writeFileSync(new URL('../docs/marathi-review.md', import.meta.url), lines.join('\n'))
console.log(`docs/marathi-review.md written — ${keys.length} strings awaiting Marathi`)
